lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    lovelace-yaml:
      mode: yaml
#      resources: !include lovelace-resources.yaml
      title: YAML
      icon: mdi:script
      show_in_sidebar: true
      filename: ui/ui-lovelace.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes
sensor: !include_dir_named sensors
binary_sensor: !include_dir_named binary_sensors 
device_tracker:
  - platform: ping
    hosts:
      router: 192.168.50.1
      cloudflare: 1.1.1.1

