lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    lovelace-yaml:
      mode: yaml
#      resources: !include lovelace-resources.yaml <--shows a syntax error
      title: YAML
      icon: mdi:script
      show_in_sidebar: true
      filename: ui/ui-lovelace.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# resources: !include lovelace-resources.yaml <--fails
input_number: !include inputs/input_number.yaml
input_datetime: !include inputs/input_datetime.yaml
input_text: !include inputs/input_text.yaml
input_select: !include inputs/input_select.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors 

device_tracker:
  - platform: ping
    hosts:
      router: 192.168.50.1
      cloudflare: 1.1.1.1
logger:
  default: info
  logs:
    custom_components.multiscrape: debug
