- platform: feedparser
  name: NASA ISS Station Report
  feed_url: https://blogs.nasa.gov/stationreport/feed/
  date_format: '%a, %d %b %Y %H:%M:%S %z'
  show_topn: 10
  scan_interval:
    hours: 1

#- platform: rest
#  name: NOAA Space Weather Alerts
#  resource: https://services.swpc.noaa.gov/products/alerts.json
#  value_template: "{{ value_json.product_id | int }}"

# - platform: moon

#- platform: ha_skyfield - HACS - https://github.com/partofthething/ha_skyfield
#- platform: ha_skyfield

#- platform: noaa_space_weather

