# Social sensors

- platform: rest
  name: Reddit Profile (zoopster)
  resource: http://reddit.com/user/johnmpugh/about.json
  value_template: "{{ value_json.data.total_karma | int }}"
  unit_of_measurement: "karma"
  json_attributes_path: "$.data"
  json_attributes:
    - total_karma
    - link_karma
    - comment_karma
    - awardee_karma
    - awarder_karma
