# P-House Dashboard for Home Assistant
# Updated for P-House configuration

title: P-House

views:
  - !include views/summary.yaml
  - !include views/lights.yaml
  - !include views/security.yaml
  - !include views/energy.yaml
  - !include views/network.yaml
  - !include views/environment.yaml
  - !include views/me.yaml
  - !include views/maintenance.yaml
  - !include views/astrometrics.yaml

decluttering_templates: !include templates/decluttering-card.yaml
button_card_templates: !include_dir_merge_named templates/button-card/
apexcharts_card_templates: !include templates/apexcharts-card.yaml

swipe_nav:
  animate: swipe
  prevent_default: true

kiosk_mode:
  user_settings:
    - users:
        - jpugh
      hide_sidebar: true
      hide_menubutton: true
      hide_overflow: true
  mobile_settings:
    hide_menubutton: true
    hide_overflow: true
